src/Addresses/urls.py
from django.conf.urls import url
from .views import checkout_address_view ,checkout_address_reuse_view

urlpatterns = [

    url(r'^checkout/$', checkout_address_view, name="checkout_address_view"),
    url(r'^checkout/reuse/$', checkout_address_reuse_view, name="checkout_address_reuse_view"),
]

src/Carts/urls.py
from django.conf.urls import url, include
from .views import cart_home, cart_update, cart_checkout


urlpatterns = [
    url(r'^cart/$',cart_home, name="cart_home"),
    url(r'^cart/update/$',cart_update, name="cart_update"),
    url(r'^cart/checkout/$',cart_checkout, name="cart_checkout"),
]

src/Home/urls.py
from django.conf.urls import url, include
from .views import home_page, index_page


urlpatterns = [
    url(r'^$',index_page, name="index_page"),
    url(r'^home/$',home_page, name="home_page"),
]

src/Products/urls.py
from django.conf.urls import url
from .views import ProductListView

urlpatterns=[
    url(r'^products/$', ProductListView.as_view(), name='products'),
]

src/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# custom views


urlpatterns = [
    url(r'^', include("Home.urls", namespace="Home")),
    url(r'^', include("registeration.urls", namespace="registration")),
    url(r'^', include("Products.urls", namespace="Products")),
    url(r'^', include("Carts.urls", namespace="Carts")),
    url(r'^', include("Addresses.urls", namespace="Addresses")),
    url(r'^admin/', admin.site.urls),
]

src/registeration/urls.py
from django.conf.urls import url
from .views import SignUp, login_user, logout_user, guest_register_view

urlpatterns=[
    url(r'^signup/$', SignUp, name='signup'),
    url(r'^login/$', login_user, name='login'),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
]

src/Addresses/models.py
from django.db import models
from billing.models import UserBillingProfile

class Address(models.Model):
    billing_profile=models.ForeignKey(UserBillingProfile)
    address_line_1 = models.CharField(max_length=150)
    address_line_2 = models.CharField(max_length=150, null=True, blank=True)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    state =models.CharField(max_length=50)

    def __str__(self):
        return str(self.billing_profile)

src/Carts/models.py
from decimal import Decimal
from django.db import models
from Products.models import Product
from django.conf import settings
from django.db.models.signals import m2m_changed, pre_save

User = settings.AUTH_USER_MODEL

class CartManger(models.Manager):
    def new_or_get(self, request):
        cart_id=request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count()==1 and qs.exists:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj =True
            request.session['cart_id']= cart_obj.id
        return cart_obj , new_obj

    def new(self, user=None):
        user_obj=None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user            =models.ForeignKey(User, null=True, blank=True)
    products        =models.ManyToManyField(Product, blank=True)
    subtotal        =models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    total           =models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    updated         =models.DateTimeField(auto_now=True)
    timestamp       =models.DateTimeField(auto_now_add=True)

    objects = CartManger()

    def __str__(self):
        return str(self.timestamp)



def m2m_changed_cart_receiver(sender, instance, action,*args, **kwargs):
    if action == 'post_add' or action=='post_remove' or  action == 'post_clear':
        products = instance.products.all()
        total_price = 0
        for product in products:
            total_price += product.price
        if instance.subtotal != total_price:
            instance.subtotal = total_price
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args,**kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.12)
    else:
        instance.total = 0

pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/Products/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Product(models.Model):
    title           = models.CharField(max_length=100)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2, max_digits=10)
    quantity        = models.IntegerField(default=0, validators=[MaxValueValidator(50), MinValueValidator(0)])

    def __str__(self):
        return self.title

src/Addresses/forms.py
from django import forms
from .models import Address

class AddressForm(forms.ModelForm):
    address_line_1 = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'Enter Delivery Address',
    }))
    address_line_2= forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'Enter nearby landmark',
    }))
    city=forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'Enter Your city',
    }))
    state=forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'Enter Your state',
    }))
    postal_code=forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder': 'Enter Pincode',
    }))
    class Meta:
        model = Address
        fields = (
            '__all__'
        )
        exclude=('billing_profile',)

src/Addresses/views.py
import time
from django.shortcuts import render, redirect
from .forms import AddressForm
from .models import Address
from billing.models import UserBillingProfile
from Carts.models import Cart
from Orders.models import Order
from django.utils.http import is_safe_url

def checkout_address_view(request):
    form = AddressForm(request.POST or None)
    context = {'form': form}
    next_get=request.GET.get('next')
    next_post=request.POST.get('next')
    redirect_path = next_get or next_post

    cart_obj, new_cart = Cart.objects.new_or_get(request)
    billing_profile, billing_profile_created = UserBillingProfile.objects.new_or_get(request)

    if billing_profile is not None:
        order_obj, order_obj_created =Order.objects.new_or_get(billing_profile, cart_obj)

    if form.is_valid():
        print(request.POST)
        instance = form.save(commit=False)
        billing_profile, billing_profile_created = UserBillingProfile.objects.new_or_get(request)
        if billing_profile is not None:
            instance.billing_profile = billing_profile
            instance.save()
            request.session["address_id"] = instance.id

        else:
            print("Error")

        if request.method == "POST":
            is_done = order_obj.check_done()
            print(is_done)
            if is_done:
                order_obj.mark_paid()
                print("paid")
                del request.session['cart_id']

        if is_safe_url(redirect_path, request.get_host()):
            return redirect(redirect_path)
        else:
            print("Error please sort it out")
            return redirect("Carts:cart_home")

    return redirect("Carts:cart_home")


def checkout_address_reuse_view(request):
    if request.user.is_authenticated():
        next_get=request.GET.get('next')
        next_post=request.POST.get('next')
        redirect_path = next_get or next_post or None
        if request.method == "POST":
            print(request.POST)
            delivery_address_id = request.POST.get("address", None)
            billing_profile, billing_profile_created = UserBillingProfile.objects.new_or_get(request)
            if billing_profile is not None:
                cart_obj, new_cart = Cart.objects.new_or_get(request)
                order_obj, order_obj_created =Order.objects.new_or_get(billing_profile, cart_obj)
            if delivery_address_id is not None:
                qs = Address.objects.filter(billing_profile=billing_profile, id=delivery_address_id)
                if qs.exists():
                    request.session["address_id"] = delivery_address_id
                if is_safe_url(redirect_path, request.get_host()):
                    return redirect(redirect_path)
    return redirect("Carts:cart_home")

src/Carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import Cart
from Products.models import Product
from Orders.models import Order
from billing.models import UserBillingProfile
from registeration.models import GuestEmail
from registeration.forms import RegisterForm, LoginForm, GuestForm
from Addresses.forms import AddressForm
from Addresses.models import Address

def cart_home(request):
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    cart_obj, new_cart = Cart.objects.new_or_get(request)
    order_obj = None
    address_id = request.session.get("address_id", None)
    billing_profile, billing_profile_created = UserBillingProfile.objects.new_or_get(request)
    address_qs = None
    for key, value in request.session.items(): print('{} => {}'.format(key, value))
    if billing_profile is not None:
        address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created =Order.objects.new_or_get(billing_profile, cart_obj)
        if address_id:
            order_obj.delivery_address = Address.objects.get(id=address_id)
            request.session['cart_product_count'] = 0
            del request.session['address_id']
            order_obj.save()

    context={
    "cart":cart_obj,
    "login_form":login_form,
    "guest_form":guest_form,
    'order':order_obj,
    "billing_profile":billing_profile,
    "address_form":address_form,
    "address_qs":address_qs
    }
    return render(request, "Carts/cart-home.html", context)


def cart_update(request):
    product_id=request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            return Http404("Product does not exist!")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            product_added = False
        else:
            cart_obj.products.add(product_obj)
            product_added = True

        request.session['cart_product_count']= cart_obj.products.count()
        if request.is_ajax():
            print("Ajax")
            json_data = {
                "added": product_added,
                "removed": not product_added,
                "cartProductCount": cart_obj.products.count()
            }
            return JsonResponse(json_data)
    return redirect("Carts:cart_home")


def cart_checkout(request):
    return render(request, "Carts/success.html", {})

src/Products/views.py
from django.shortcuts import render

from django.shortcuts import render
from django.views.generic import ListView

from .models import Product
from Carts.models import Cart

class ProductListView(ListView):
    queryset = Product.objects.all()
    template_name = "Products/ProductList.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        request = self.request
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        context['cart']= cart_obj
        return context

src/templates/Snippets/address-form.html
<form class="needs-validation" method="post" action="{% if action_url %}{{ action_url }}{% endif %}" novalidate>
  {% csrf_token %}
  {% if next_url %}
  <input type="hidden" name="next" value="{{next_url}}">
  {% endif %}
    <div class="col-md-12 mb-2">
      <label for="address">Address</label>
      {{form.address_line_1}}
      <div class="invalid-feedback">
        Please enter your address.
      </div>
    </div>
    <div class="col-md-12 mb-2">
      <label for="address-2">Landmark</label>
      {{form.address_line_2}}
      <div class="invalid-feedback">
        Please enter your address.
      </div>
    </div>
    <div class="col-md-12 mb-2">
      <label for="address-2">Pincode</label>
      {{form.postal_code}}
      <div class="invalid-feedback">
        Please enter your pincode.
      </div>
    </div>
    <div class="col-md-12 mb-2">
      <label for="address-2">State</label>
      {{form.state}}
      <div class="invalid-feedback">
        Please enter your state.
      </div>
    </div>
    <div class="col-md-12 mb-2">
      <label for="address-2">City</label>
      {{form.city}}
      <div class="invalid-feedback">
        Please enter your city.
      </div>
    </div>
    <div class="col-md-12 mb-2">
        <button class="btn btn-block btn-secondary" type="submit">Save and Continue</button>
    </div>
</form>

src/templates/Snippets/bootstrap-checkout-form.html
# css
.container {
  max-width: 960px;
}

.border-top { border-top: 1px solid #e5e5e5; }
.border-bottom { border-bottom: 1px solid #e5e5e5; }
.border-top-gray { border-top-color: #adb5bd; }

.box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

.lh-condensed { line-height: 1.25; }

#html
<body class="bg-light">

    <div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h2>Checkout form</h2>
        <p class="lead">Below is an example form built entirely with Bootstrap's form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
      </div>

      <div class="row">
        
        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Billing address</h4>
          <form class="needs-validation" novalidate>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="firstName">First name</label>
                <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Last name</label>
                <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label for="username">Username</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">@</span>
                </div>
                <input type="text" class="form-control" id="username" placeholder="Username" required>
                <div class="invalid-feedback" style="width: 100%;">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label for="email">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" class="form-control" id="email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="mb-3">
              <label for="address">Address</label>
              <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="mb-3">
              <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="row">
              <div class="col-md-5 mb-3">
                <label for="country">Country</label>
                <select class="custom-select d-block w-100" id="country" required>
                  <option value="">Choose...</option>
                  <option>United States</option>
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
              <div class="col-md-4 mb-3">
                <label for="state">State</label>
                <select class="custom-select d-block w-100" id="state" required>
                  <option value="">Choose...</option>
                  <option>California</option>
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
              <div class="col-md-3 mb-3">
                <label for="zip">Zip</label>
                <input type="text" class="form-control" id="zip" placeholder="" required>
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>
            <hr class="mb-4">
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="same-address">
              <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
            </div>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="save-info">
              <label class="custom-control-label" for="save-info">Save this information for next time</label>
            </div>
            <hr class="mb-4">

            <h4 class="mb-3">Payment</h4>

            <div class="d-block my-3">
              <div class="custom-control custom-radio">
                <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
                <label class="custom-control-label" for="credit">Credit card</label>
              </div>
              <div class="custom-control custom-radio">
                <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="debit">Debit card</label>
              </div>
              <div class="custom-control custom-radio">
                <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="paypal">Paypal</label>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="cc-name">Name on card</label>
                <input type="text" class="form-control" id="cc-name" placeholder="" required>
                <small class="text-muted">Full name as displayed on card</small>
                <div class="invalid-feedback">
                  Name on card is required
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="cc-number">Credit card number</label>
                <input type="text" class="form-control" id="cc-number" placeholder="" required>
                <div class="invalid-feedback">
                  Credit card number is required
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 mb-3">
                <label for="cc-expiration">Expiration</label>
                <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                <div class="invalid-feedback">
                  Expiration date required
                </div>
              </div>
              <div class="col-md-3 mb-3">
                <label for="cc-expiration">CVV</label>
                <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                <div class="invalid-feedback">
                  Security code required
                </div>
              </div>
            </div>
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
          </form>
        </div>
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; 2017-2018 Company Name</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="#">Privacy</a></li>
          <li class="list-inline-item"><a href="#">Terms</a></li>
          <li class="list-inline-item"><a href="#">Support</a></li>
        </ul>
      </footer>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
  </body>

src/templates/Snippets/brand.html
{% load staticfiles %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/Home/main_page.css' %}">
{% endblock %}

<div class="container-fluid nav-pattern">
  <nav class="navbar">
    <a class="navbar-brand" href="{% url 'Home:home_page' %}">
      <img class="logo_image" src="{% static 'images/desizaikalogo.png' %}" width="240" height="100" alt="">
    </a>
    {% include 'Snippets/nav.html' %}
  </nav>
</div>

src/templates/Snippets/checkout-signin.html
<form action="{% url 'registration:login' %}" method="post" class="ml-3">
  {% csrf_token %}
  {% if next_url %}
    <input type="hidden" name="next" value="{{next_url}}">
  {% endif %}
  <div class="mb-2">
    <label>Username</label>
    {{form.username}}
  </div>
  <div class="mb-2">
    <label>Password</label>
    {{form.password}}
  </div>

  <button class="btn btn-block" type="submit" name="button">Signin</button>
</form>

src/templates/Snippets/choose-address.html
{% if address_qs.exists %}
<form method="post" action="{{ action_url }}">
  {% csrf_token %}
  {% if next_url %}
  <input type="hidden" name="next" value="{{next_url}}">
  {% endif %}
  {% for address in address_qs %}
  <div class="inputGroup">
    <label for="address-{{address.id}}">
        <input class="address" type="radio" id="address-{{address.id}}" value="{{address.id}}" name="address">
        {{address.address_line_1}}
        {{address.address_line_2}}
        {{address.postal_code}}
        </input>
    </label><br/>
  </div>
  {% endfor %}
  <button type="submit" name="button" class="btn btn-block btn-secondary">Select an Address</button>
</form>
{% endif %}

src/templates/Snippets/guest-checkout-form.html
<form class="needs-validation" method="post" action="{% if action_url %}{{ action_url }}{% else %}{% url 'registration:login' %}{% endif %}" novalidate>
  {% csrf_token %}
  {% if next_url %}
  <input type="hidden" name="next" value="{{next_url}}">
  {% endif %}
  <div class="col-md-12  mb-2">
    <label for="FullName">Full Name</label>
    {{form.name}}
    <div class="invalid-feedback">
      Valid name is required.
    </div>
  </div>
  <div class="col-md-12 mb-2">
    <label for="email">Email</label>
    {{form.email}}
    <div class="invalid-feedback">
      Please enter a valid email address.
    </div>
  </div>
  <div class="col-md-12 mb-2">
    <button class="btn btn-block" type="submit" name="Submit">Submit</button>
  </div>
</form>

src/templates/Snippets/nav.html
  <nav class="nav justify-content-end">
    <a class="nav-link" href="{% url 'Products:products' %}" style="color:#800000">Menu</a>
    <a class="nav-link" href="#" style="color:#800000">Events</a>

    <a class="nav-link cart" href="{% url 'Carts:cart_home' %}" style="color:#800000">{% if request.session.cart_product_count %}<span class="products-in-the-cart">{{request.session.cart_product_count}}</span>{% endif %}Cart</a>

    {% if user.is_authenticated %}
    <a name="Signin" class="nav-link" href="{% url 'registration:logout' %}" style="color:#800000">Logout</a>
    {% else %}
    <a name="Signin" class="nav-link" href="{% url 'registration:login' %}" style="color:#800000">Signin</a>
    <a name="Register" class="nav-link" href="{% url 'registration:signup' %}" style="color:#800000">Register</a>
    {% endif %}
  </nav>

src/templates/Snippets/product.html
{% load staticfiles %}


{% block css %}
  <link rel="stylesheet" href="{% static 'css/Products/product.css' %}">
{% endblock %}

{% for product in product_list %}
<div class="product">
  <div class="imgbox">
    <img src="{% static 'images/product-images/product-image1.jpg' %}" alt="image missing">
  </div>
  <div class="details">
    <h2>{{product.title}}</h2>
    <h4 class="price">
      {{product.price}}
    </h4>
    <p class="description">{{product.description}}</p>
    <form class="add-product" action="{% url 'Carts:cart_update' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="product_id" value="{{product.id}}">
      <span class="buttonArea">
      {% if product in cart.products.all %}
        <button type="submit" class="add-to-cart-button">Remove</button>
      {% else %}
        <button  type="submit" class="add-to-cart-button">Add To Cart</button>
      {% endif %}
      </span>
    </form>
  </div>
</div>
{% endfor %}

src/templates/Snippets/timeline.html
{% load staticfiles %}
<div class="container-fluid mt-5 mb-5">
	<div class="row">
		{% if cart.products.exists %}
			{% if not order.delivery_address %}
				{% include 'Snippets/cart.html' %}
			{% endif %}
		{% else %}
			<div class="mb-3 text-center col-md-12">
				<h4 class="mt-1">Your Cart is Empty</h4>
			</div>
		{% endif %}

		{% if order.delivery_address %}
		<div style="width:100%" class="align-items-center justify-align-center">
			<div class="col-md-7 offset-md-3 mb-4">

				<h3 class="text-center">Your order id is {{order.order_id}}</h3>

				<div class="jumbotron">
					<table class="table table-borderless">
					  <tbody>
					    <tr>
					      <th scope="row">Delivery Address&nbsp;:</th>
					      <td>{{order.delivery_address.address_line_1}},{{order.delivery_address.address_line_2}},{{order.delivery_address.state}},{{order.delivery_address.city}},{{order.delivery_address.postal_code}}</td>
					    </tr>
					    <tr>
					      <th scope="row">Cart Items&nbsp;:</th>
					      <td>{% for product in cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
					    </tr>
					    <tr>
					      <th scope="row">Cart Total&nbsp;:</th>
					      <td colspan="2">{{cart.total}}</td>
					    </tr>
							<tr>
					      <th scope="row">Delivery Charges&nbsp;:</th>
								{% if order.delivery_charges == 0  %}
								<td colspan="2">Free</td>
								{% else %}
					      <td colspan="2">{{order.delivery_charges}}</td>
								{% endif %}
					    </tr>
							<tr>
					      <th scope="row">Order Total<small>(inclusive of 10% Taxes)</small>&nbsp;:</th>
					      <td colspan="2">{{order.order_total}}</td>
					    </tr>
							<tr>
								<th colspan="1"></th>
								<td>
									<form method="post" action="{% url 'Carts:cart_checkout' %}">
										{% csrf_token %}
									<button type="submit" name="proceed-to-payment" class="btn btn-block btn-warning text-light">Proceed To Payment</button>
									</form>
								</td>
							</tr>
					  </tbody>
					</table>
				</div>
			</div>
			</div>
		{% endif %}

		<div class="col-md-4">
			{% if not billing_profile %}
				{% if cart.products.exists %}
						<h4>Continue Shopping</h4>
							<ul class="timeline">
								<li>
									<h4 class="mb-2">Fill out your details(Continue as a Guest)</h4>
									{% url "registration:guest_register" as guest_register_url %}
									{% include 'Snippets/guest-checkout-form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url%}
								</li>
							</ul>
				{% endif %}
			{% else %}
					{% if cart.products.exists %}
					{% if not order.delivery_address %}
							<div class="col-md">
								<ul class="timeline mt-5">
									<li>
									<h4 class="mb-2">Checkout</h4>
									<hr/>
									{% url "Addresses:checkout_address_view" as checkout_address_url %}
									{% include 'Snippets/address-form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_url %}
									</li>
								</ul>
						</div>
						{% endif %}
					{% endif %}
			{% endif %}
		</div>
			{% if cart.products.exists %}
				{% if address_qs.exists  %}
				{% if request.user.is_authenticated %}
				{% if not order.delivery_address %}
					<div class="col-md">
						<ul class="timeline mt-5">
							<li>
							<h4 class="mb-2">Choose an Address</h4>
							<hr/>
							{% url "Addresses:checkout_address_reuse_view" as checkout_address_reuse_url %}
							{% include 'Snippets/choose-address.html' with address_qs=address_qs next_url=request.build_absolute_uri action_url=checkout_address_reuse_url %}
							</li>
						</ul>
					</div>
					{% endif %}
					{% endif %}
				{% endif %}
			{% endif %}

			{% if not billing_profile %}
				{% if cart.products.exists %}
					<div class="col-md-4">
						<ul class="timeline mt-5">
							<li>
							<h4 class="mb-2 ml-1">Signin(if you already have an existing account)</h4>
							<div class="checkout-signin-button align-items-center">
								{% include 'Snippets/checkout-signin.html' with form=login_form next_url=request.build_absolute_uri %}
							</div>
							</li>
						</ul>
					</div>
					{% endif %}
				{% endif %}
		</div>
	</div>